language: python
python:
- '3.6'
script:
- "./scripts/download-s3-model.sh"
- "./scripts/build-web-package.sh"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA52CGVFQZQPZPXF5T
  secret_access_key:
    secure: VPzbLyADan9b7AFWxZt2M9Oqs2eY7UQK65pdwaaO0S7Uh2e8ymTqqv51r2WIvzHLj0QOx2WQiDdKlZqvQdYmvh3UznQZWBFXUqjX+EBr2B2b4mfsQYsGUPVAwV1WRgrdy1FgULDjCosp34kH2ROFD8Bt6pgAAmrrLQI7KHZdWYWKTNlSJLcinCkr8IqqN1q2onKvUNRWIy2YfDwunHxNNNI7rAQ6tpaUMZPguFB3edXlAmzOCAiOK7w4Ha4Hr7e5Ra2uK/CQ9TgRInjul2HLooCzgvyFPTwZkS1xBCUzAS3yyMznwmcJ7lxTxE5UWfpPGu3jmL49Ca0QN3qKIiNLMPrN9pmcA651jsDKM7+9Uaos657v94tlpeFRLP80A4OEGQGiXYwOsD+ntGLH3FmLMahbZV5EeaE938DkKRnG0boTKCelqXZuq/CvwPbVEG2/5noHEAjLj3tRG/vO/QE0BvItVGi62xW4eT1jSMgS+X8ODlcRkY9eAh0pdsRnhbhYR2p5KcjO/PUV/+Ja0K4RbDni0uFtSLyGZWih0Gl3ee/RGvc9inEzb/ZsLjHUkq+c/UxPMn5QRpISCYNUchjfZ7LnC0Ba5RVV3eMAXR9WdJUvyJb5V1WY5Kv+OQWI1Ai9NePsR8n1w3o0Fy2SPoi5euT3ychX8oeBpizpRIW4UDs=
  region: eu-west-2
  app: LavalampRecognizer
  skip_cleanup: true
  zip_file: lavalamp_web.zip
  on:
    repo: pkedziora/lavalamp-recognizer
  bucket_name: elasticbeanstalk-eu-west-2-949335960627
  env: Lavalamprecognizer-env
