language: python
python:
- '3.6'
script:
- "./scripts/download-s3-model.sh"
- "./scripts/build-web-package.sh"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAUBRS2K73MCPSHBK4
  secret_access_key:
    secure: P4VaqcdeEDTeduNxt0RxoQ2yjNDGEVGoAfYoLk/3pAkJuGtoqmJMlYjeFx1EVth4uTChd65E9mzBRtMtHktUzJvSQQmZmG4swPatVWXILjKqCjaJtqGhstdvUJ/WmZ1mKYK6UBfePshFcmcRy6k+GVWEzUIAHQ1bg7vVh5jzV7GRYUWVYPZEDJ7WlgsvKfbq+sdtz13+z7NOXzeVC41XQ4GUU6I8l5jdTuEpldHMURAP9elhx0w5cy4BKwCNCXnMWJB4HYZlzw0TuNsQWRIY8UKczsynW82Uxg4jglP692XA1wMmKrLnO0DxeMaXjPTPDJB9KwV4lUK/Ve4byjgTjxDD1wMdnF9+iHpLAn0yDZsjIy0ruBfobTkrdcyqde0rZyvvhFXfK4dq14hcNULb4KTuqVvQ5WlPIwI2SgwAzuHqOC2YAHNX8gt+wi+CIdtrp6Q9dTWsGMWUKNCeTIQLPunxMEWPgyed9J1in3RKaZ4PcKQTMGX6Ryc+t6x5Iro+GKbBjxkxf8VrgKEncStwBEVG7hc6HPPKRXnHWg6yXh6D6dgSTfHFoP1zx2d6ftSr4zSK4BncOTz9FZi4ha6quiVq9DCfWIOucMd0vVwGQqs8R/SwIgE/FI9X+gkE2pc186HxmoitXzFbk+aqepURI8HN+uYoeKRUsQKa6lIofiI=
  region: eu-west-1
  app: lavalamp-recognizer
  skip_cleanup: true
  zip_file: lavalamp_web.zip
  on:
    repo: pkedziora/lavalamp-recognizer  
  bucket_name: elasticbeanstalk-eu-west-1-278205716470
  env: LavalampRecognizer-env
