language: python
python:
- '3.6'
script:
- "./scripts/download-s3-model.sh"
- "./scripts/build-web-package.sh"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA6D57VD5BGUOBU6GC
  secret_access_key:
    secure: EehTx4r9VT7J/dCrVtGJIJ52d/OM5erkbHmEnDNVFsaQVEvFvrTefQPdiZ768qJJOPlc3slkUFnuGzG5j1jMeWPI5yLL+gNB2Fy2B+vrZ6LkoAVLmpx1aUQbUKYPPj27SR+J+WXTjnvpw8392HYfo4Iij+TSPIgysa31yewOOq1qcmb/5REnYZCfiB4zGQz2speOZWBPPqsJtTA9VKBKmCmC21Kbxc3lDyQ0sN6chDrARmNNQRmmW3WrQ2jVXi5CehKdnfxFlGBXiYvKWmkAvjrXkMQPGlV3wALAHDv8m1Tn0ulMQ2+m5pD+d6DtqAojEF/rDCWzUFg9PlDG2GxJbzcEQcLetARfjnFa8s75MJ9we37vptJFKAleFU2rqg+H2prr9DXSQcgAi5YHRVPkvgDTcgEK/R5Yr7JCWnB8yS4J34amPD81jOaacoocO5HNdGkc7uIjgiDNWFLXgMwtWnCFS4bQD+99dU/yAnJKEOf1AonYZmEPUw9bgkvi2KRvwOAh8PEV5VeIOK+zJINRjzRNtLqlaBrmYUNsoeMeq3+OpDTCQd/N54cuB0P8/22K0A4Gamo1DZ+R0aJnUFdn7NZQ5ukv8gzmCTZxuR5r2DgWJnJrZCaA2mibOs9ejdQicrLBnoDmw1YMF71WFpuYOl1HjdTP/QU0zReOO/clIoY=
  region: eu-west-1
  app: lavalamp-recognizer
  env: LavalampRecognizer-env-1
  skip_cleanup: true
  zip_file: lavalamp_web.zip
  on:
    repo: pkedziora/lavalamp-recognizer
